name: womanly_mobile
description: A new Flutter project.

publish_to: 'none'
version: 1.0.172+172

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  adjust_sdk: ^4.33.0
  amplitude_flutter: ^3.8.1
  animated_flip_counter: ^0.2.4
  animations: ^2.0.4
  app_settings: ^4.2.0
  app_tracking_transparency: ^2.0.2+4
  appsflyer_sdk: ^6.8.2
  async: ^2.6.1
  audio_session: ^0.1.6+1
  cached_network_image: ^3.2.3
  circular_reveal_animation: ^2.0.1
  connectivity_plus: ^2.3.0
  cupertino_icons: ^1.0.2
  delayed_widget: ^1.1.2
  device_info_plus: ^4.1.2
  easy_localization: ^3.0.0
  equatable: ^2.0.3
  external_app_launcher: ^3.1.0
  facebook_app_events: ^0.17.0
  firebase_analytics: ^10.0.7
  firebase_core: ^2.4.0
  firebase_crashlytics: ^3.0.7
  firebase_messaging: ^14.1.4
  firebase_remote_config: ^3.0.7
  flip_card: ^0.6.0
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.3.0
  flutter_easyloading: ^3.0.5
  flutter_localizations:
    sdk: flutter
  flutter_native_timezone: ^2.0.0
  flutter_rating_bar: ^4.0.1
  # flutter_showcaseview: ^2.1.3
  showcaseview: ^2.0.2
  flutter_staggered_animations: ^1.1.1
  hive: ^2.2.3
  http: ^0.13.4
  image: ^3.1.3
  in_app_review: ^2.0.4
  json_annotation: ^4.4.0
  json_serializable: ^6.1.5
  just_audio: ^0.9.20
  just_audio_background: ^0.0.1-beta.5
  marquee: ^2.2.1
  package_info_plus: ^1.4.3+1
  path_provider: ^2.0.2
  provider: ^5.0.0
  pull_to_refresh: ^2.0.0
  resize: ^1.0.0
  restart_app: ^1.1.0+1
  screenshot: ^1.2.3
  share_plus: ^4.0.10
  shared_preferences: ^2.0.13
  shimmer: ^2.0.0
  shimmer_image: ^0.0.2
  social_share: 2.2.1
  stack_blur: ^0.2.2
  url_launcher: ^6.1.0
  uuid: ^3.0.6

dev_dependencies:
  auto_route_generator: ^3.2.3
  build_runner: ^2.1.7

  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/icons/
    - assets/images/icons/emoji/

  fonts:
    - family: Manrope
      fonts:
        - asset: assets/fonts/Manrope-ExtraLight.ttf
        - asset: assets/fonts/Manrope-Light.ttf
        - asset: assets/fonts/Manrope-Regular.ttf
        - asset: assets/fonts/Manrope-Medium.ttf
        - asset: assets/fonts/Manrope-SemiBold.ttf
        - asset: assets/fonts/Manrope-Bold.ttf
        - asset: assets/fonts/Manrope-ExtraBold.ttf
    - family: Merriweather
      fonts:
        - asset: assets/fonts/Merriweather-Light.ttf
        - asset: assets/fonts/Merriweather-Regular.ttf
        - asset: assets/fonts/Merriweather-Bold.ttf
        - asset: assets/fonts/Merriweather-Black.ttf
